package dev.supergrecko.kllvm.core.enumerations

import dev.supergrecko.kllvm.contracts.OrderedEnum
import org.bytedeco.llvm.global.LLVM

public enum class LLVMCallConv(public override val value: Int) : OrderedEnum<Int> {
    CCallConv(LLVM.LLVMCCallConv),
    FastCallConv(LLVM.LLVMFastCallConv),
    ColdCallConv(LLVM.LLVMColdCallConv),
    GHCCallConv(LLVM.LLVMGHCCallConv),
    HiPECallConv(LLVM.LLVMHiPECallConv),
    WebKitJSCallConv(LLVM.LLVMWebKitJSCallConv),
    AnyRegCallConv(LLVM.LLVMAnyRegCallConv),
    PreserveMostCallConv(LLVM.LLVMPreserveMostCallConv),
    PreserveAllCallConv(LLVM.LLVMPreserveAllCallConv),
    SwiftCallConv(LLVM.LLVMSwiftCallConv),
    CXXFASTTLSCallConv(LLVM.LLVMCXXFASTTLSCallConv),
    X86StdcallCallConv(LLVM.LLVMX86StdcallCallConv),
    X86FastcallCallConv(LLVM.LLVMX86FastcallCallConv),
    ARMAPCSCallConv(LLVM.LLVMARMAPCSCallConv),
    ARMAAPCSCallConv(LLVM.LLVMARMAAPCSCallConv),
    ARMAAPCSVFPCallConv(LLVM.LLVMARMAAPCSVFPCallConv),
    MSP430INTRCallConv(LLVM.LLVMMSP430INTRCallConv),
    X86ThisCallCallConv(LLVM.LLVMX86ThisCallCallConv),
    PTXKernelCallConv(LLVM.LLVMPTXKernelCallConv),
    PTXDeviceCallConv(LLVM.LLVMPTXDeviceCallConv),
    SPIRFUNCCallConv(LLVM.LLVMSPIRFUNCCallConv),
    SPIRKERNELCallConv(LLVM.LLVMSPIRKERNELCallConv),
    IntelOCLBICallConv(LLVM.LLVMIntelOCLBICallConv),
    X8664SysVCallConv(LLVM.LLVMX8664SysVCallConv),
    Win64CallConv(LLVM.LLVMWin64CallConv),
    X86VectorCallCallConv(LLVM.LLVMX86VectorCallCallConv),
    HHVMCallConv(LLVM.LLVMHHVMCallConv),
    HHVMCCallConv(LLVM.LLVMHHVMCCallConv),
    X86INTRCallConv(LLVM.LLVMX86INTRCallConv),
    AVRINTRCallConv(LLVM.LLVMAVRINTRCallConv),
    AVRSIGNALCallConv(LLVM.LLVMAVRSIGNALCallConv),
    AVRBUILTINCallConv(LLVM.LLVMAVRBUILTINCallConv),
    AMDGPUVSCallConv(LLVM.LLVMAMDGPUVSCallConv),
    AMDGPUGSCallConv(LLVM.LLVMAMDGPUGSCallConv),
    AMDGPUPSCallConv(LLVM.LLVMAMDGPUPSCallConv),
    AMDGPUCSCallConv(LLVM.LLVMAMDGPUCSCallConv),
    AMDGPUKERNELCallConv(LLVM.LLVMAMDGPUKERNELCallConv),
    X86RegCallCallConv(LLVM.LLVMX86RegCallCallConv),
    AMDGPUHSCallConv(LLVM.LLVMAMDGPUHSCallConv),
    MSP430BUILTINCallConv(LLVM.LLVMMSP430BUILTINCallConv),
    AMDGPULSCallConv(LLVM.LLVMAMDGPULSCallConv),
    AMDGPUESCallConv(LLVM.LLVMAMDGPUESCallConv)
}